**NumPy Getting Started**

In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

In [3]:
value=np.array([1,2,3,4,5,6,7])

In [4]:
value

array([1, 2, 3, 4, 5, 6, 7])

**NumPy Creating Arrays**

In [5]:
arr=np.array(45)

In [6]:
arr

array(45)

In [7]:
#1d array


In [8]:
arr1=np.array([1,2,3,4,5,6])

In [9]:
arr1

array([1, 2, 3, 4, 5, 6])

In [10]:
#2d array

In [11]:
arr2=np.array([[1,2,3],[4,5,6]])

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#3d Array

In [14]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
#check number of dimention in a array

In [18]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:
higher_diimensiion=np.array([1,2,3],ndmin=5)
print(higher_diimensiion)
print("The dimention of the array is:",higher_diimensiion.ndim)



[[[[[1 2 3]]]]]
The dimention of the array is: 5


**Array Indexing**

In [22]:
arr=np.array([1, 2, 3, 4, 5, 6])

In [23]:
arr[0]

1

In [24]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
arr3[2,2]

9

In [26]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


**NumPy Array Slicing**

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [33]:
#slicing 2d arrays

In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])

[7 8 9]


In [36]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [37]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


**NumPy Data Types**

In [45]:
'''Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )'''


'Below is a list of all data types in NumPy and the characters used to represent them.\n\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )'

In [46]:
arr = np.array([1, 2, 3, 4])

In [53]:
arr.dtype

dtype('int32')

In [54]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [55]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [59]:
#Converting Data Type on Existing Arrays
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [61]:
#Change data type from integer to boolean:
arr = np.array([1.1, 0, 3.1])
newarr=arr.astype('bool')
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


**NumPy Array Copy VS View**

In [ ]:
#The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.


In [63]:
#copy array
arr=np.array([1,2,3,4,5,6])
newarr=arr.copy()
arr[0]=42
print(arr)
print(newarr)

[42  2  3  4  5  6]
[1 2 3 4 5 6]


In [64]:
#View array
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [65]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


**NumPy Array Shape**

In [66]:
#The shape of an array is the number of elements in each dimension.
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [67]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [68]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Iterating Arrays**

In [71]:
#Iterating means going through elements one by one.
arr=np.array([1, 1, 1, 1, 4])
for n in arr:
    print(n)

1
1
1
1
4


In [70]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [72]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [73]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [74]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


**Joining NumPy Arrays**

In [75]:
#Joining means putting contents of two or more arrays in a single array.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [76]:


arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [77]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


**Splitting NumPy Arrays**

In [78]:
#Splitting is reverse operation of Joining.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [80]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


**NumPy Searching Arrays**

In [81]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


**NumPy Sorting Arrays**

In [84]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [85]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


**Filtering Arrays**

In [86]:
'''Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.'''

'Getting some elements out of an existing array and creating a new array out of them is called filtering.\n\nIn NumPy, you filter an array using a boolean index list.'

In [87]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [88]:
arr=np.array([1,2,3,4])
x=[True, False,True,False]
newarr=arr[x]
print(newarr)

[1 3]


In [89]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [90]:
arr=np.array([2,3,4,5,6,7])
new_arr=[]
for x in arr:
    if x>2:
        new_arr.append(True)
    else:
        new_arr.append(False)
array_value=arr[new_arr]
print(new_arr)
print(array_value)

[False, True, True, True, True, True]
[3 4 5 6 7]
